language: python
sudo: false
python:
  - 2.7


install:
  - pip install -r requirements.txt

script:
  - nosetests gistools.test.test_geometry
  - nosetests gistools.test.test_collection

notifications:
  email: false