language: python

python:
  - 2.7

before_install:
  - sudo apt-get update
  - sudo apt-get install python-dev

install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - nosetests gistools.test.test_geometry
  - nosetests gistools.test.test_collection
  - pytest

notifications:
  email: false