language: python

python:
  - 2.7

addons:
  apt:
    packages:
      - python-dev



install:
  - pip install -r requirements.txt

script:
  - nosetests gistools.test.test_geometry
  - nosetests gistools.test.test_collection
  - pytest

notifications:
  email: false