language: python

python:
  - 2.7

before_install:
  - sudo apt-get update
  - sudo apt-get install python-dev
  - sudo apt-get install libspatialindex

install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)

script:
  - pytest

notifications:
  email: false